# Project
archives_base_name=customizableelytra
group=com.hidoni.customizableelytra
java_version=25

# Common
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
mod_name=Customizable Elytra
mod_author=Hidoni
mod_id=customizableelytra
mod_version=2.2.9
description=Adds a variety of colorful ways to customize your elytra!
mod_credits=
license=MIT
neo_form_version=26.2-2
mixinextras_version=0.5.4

# Forge
forge_version=65.1.0
forge_loader_version_range=[65,)

# Fabric
fabric_version=0.152.0+26.2
fabric_loader_version=0.19.3
mod_menu_version=20.0.1

# NeoForge
neoforge_version=26.2.0.53-beta

# Publishing
curseforge_project_id=440047
modrinth_project_id=L25fOeGq
release_type=release
supported_versions=26.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false