# Project
archives_base_name=customizableelytra
group=com.hidoni.customizableelytra
java_version=25

# Common
minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
mod_name=Customizable Elytra
mod_author=Hidoni
mod_id=customizableelytra
mod_version=2.2.8
description=Adds a variety of colorful ways to customize your elytra!
mod_credits=
license=MIT
neo_form_version=26.1-1
mixinextras_version=0.5.4

# Forge
forge_version=62.0.9
forge_loader_version_range=[62,)

# Fabric
fabric_version=0.145.1+26.1
fabric_loader_version=0.19.2
mod_menu_version=18.0.0-beta.1

# NeoForge
neoforge_version=26.1.0.19-beta

# Publishing
curseforge_project_id=440047
modrinth_project_id=L25fOeGq
release_type=release
supported_versions=26.1,26.1.1,26.1.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false