# Project
archives_base_name=customizableelytra
group=com.hidoni.customizableelytra
java_version=21

# Common
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.21.5)
mod_name=Customizable Elytra
mod_author=Hidoni
mod_id=customizableelytra
mod_version=2.2.8
description=Adds a variety of colorful ways to customize your elytra!
mod_credits=
license=MIT
neo_form_version=1.21.4-20241203.161809
parchment_minecraft_version=1.21.4
parchment_mappings_version=2024.12.22
mixinextras_version=0.4.1

# Forge
forge_version=54.0.12
forge_loader_version_range=[54,)

# Fabric
fabric_version=0.113.0+1.21.4
fabric_loader_version=0.16.9
mod_menu_version=13.0.0-beta.1

# NeoForge
neoforge_version=21.4.46-beta
neoforge_loader_version_range=[4,)

# Publishing
curseforge_project_id=440047
modrinth_project_id=L25fOeGq
release_type=release
supported_versions=1.21.4

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false